// ─── SUPABASE ADMIN CLIENT (replaces Firebase/Firestore) ─────
// Server-only helpers powered by the service role key.

import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'  // generated by: supabase gen types typescript

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!  // server only, never expose

// Admin client — bypasses RLS, use only in workers and trusted server code
export const adminSupabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_SERVICE_KEY,
  { auth: { persistSession: false } }
)

// ─── TYPED QUERY HELPERS ──────────────────────────────────────
// Replace Firestore collection helpers with typed Supabase queries

export const db = {

  // ── PRODUCTS ──────────────────────────────────────────────

  async getProduct(slug: string) {
    const { data, error } = await adminSupabase
      .from('products')
      .select(`
        *,
        brands (*),
        categories (*),
        product_images (*),
        product_attributes (*),
        vendor_products (
          *,
          vendors (id, name, slug, avg_ship_time_days)
        )
      `)
      .eq('slug', slug)
      .eq('status', 'active')
      .single()
    if (error) throw error
    return data
  },

  async getProducts(options: {
    category?: string   // matches category_name column directly
    brand?: string      // matches brand_name column directly
    limit?: number      // page size — default 48
    offset?: number     // for pagination: page * limit
    orderBy?: 'price_asc' | 'price_desc' | 'newest'
    inStockOnly?: boolean
  } = {}) {
    const pageSize = options.limit ?? 48
    const from     = options.offset ?? 0
    const to       = from + pageSize - 1

    // Select only the columns the shop UI actually needs.
    // Avoids pulling heavy columns (search_vector, specs, etc.)
    // on a list page. getProduct() fetches the full row.
    let query = adminSupabase
      .from('products')
      .select(
        'id, sku, slug, name, brand_name, category_name, ' +
        'our_price, msrp, compare_at_price, map_price, ' +
        'in_stock, stock_quantity, is_new, images',
        { count: 'exact' }
      )
      .eq('status', 'active')

    // Filter directly on denormalized columns written by the sync.
    // category_name and brand_name live on the products row itself —
    // no join needed, and PostgREST handles these reliably.
    if (options.category)   query = query.eq('category_name', options.category)
    if (options.brand)      query = query.eq('brand_name', options.brand)
    if (options.inStockOnly) query = query.eq('in_stock', true)

    const orderMap = {
      price_asc:  { column: 'our_price',  ascending: true  },
      price_desc: { column: 'our_price',  ascending: false },
      newest:     { column: 'created_at', ascending: false },
    }
    const order = orderMap[options.orderBy ?? 'newest']
    query = query
      .order(order.column, { ascending: order.ascending })
      .range(from, to)  // Supabase hard-caps at 1000 without range()

    const { data, error, count } = await query
    if (error) throw error
    return { products: data ?? [], total: count ?? 0 }
  },

  async getProductsByVehicle(vehicleId: string, options: {
    category?: string
    limit?: number
    offset?: number
    orderBy?: 'price_asc' | 'price_desc' | 'newest'
    inStockOnly?: boolean
  } = {}) {
    // This is where Postgres DESTROYS Firestore.
    // One query with JOINs vs dozens of Firestore reads.
    let query = adminSupabase
      .from('products')
      .select(`
        *,
        brands (name, slug),
        product_images (url, is_primary),
        fitment!inner (vehicle_id)
      `, { count: 'exact' })
      .eq('fitment.vehicle_id', vehicleId)
      .eq('status', 'active')

    if (options.inStockOnly) query = query.eq('in_stock', true)
    if (options.category) query = query.eq('categories.slug', options.category)

    const orderMap = {
      price_asc: { column: 'our_price', ascending: true },
      price_desc: { column: 'our_price', ascending: false },
      newest: { column: 'created_at', ascending: false },
    }
    const order = orderMap[options.orderBy ?? 'newest']
    query = query.order(order.column, { ascending: order.ascending })

    if (options.limit) query = query.limit(options.limit)
    if (options.offset) query = query.range(options.offset, (options.offset + (options.limit ?? 48)) - 1)

    const { data, error, count } = await query
    if (error) throw error
    return { products: data, total: count }
  },

  async searchProducts(searchTerm: string, filters: {
    vehicleId?: string
    category?: string
    brand?: string
    minPrice?: number
    maxPrice?: number
    inStock?: boolean
    limit?: number
    offset?: number
  } = {}) {
    // Full-text search using the tsvector column we created
    let query = adminSupabase
      .from('products')
      .select(`
        *,
        brands (name, slug),
        product_images (url, is_primary)
      `, { count: 'exact' })
      .textSearch('search_vector', searchTerm, { type: 'websearch' })
      .eq('status', 'active')

    if (filters.vehicleId) {
      // Add fitment JOIN for vehicle-specific search
      query = query.eq('fitment.vehicle_id', filters.vehicleId)
    }
    if (filters.inStock) query = query.eq('in_stock', true)
    if (filters.minPrice) query = query.gte('our_price', filters.minPrice)
    if (filters.maxPrice) query = query.lte('our_price', filters.maxPrice)
    if (filters.brand) query = query.eq('brands.slug', filters.brand)
    if (filters.limit) query = query.limit(filters.limit)

    const { data, error, count } = await query
    if (error) throw error
    return { products: data, total: count }
  },

  // ── USERS ──────────────────────────────────────────────────

  async getUserProfile(userId: string) {
    const { data, error } = await adminSupabase
      .from('user_profiles')
      .select(`
        *,
        user_garage (
          *,
          vehicles (*)
        ),
        user_addresses (*)
      `)
      .eq('id', userId)
      .single()
    if (error) throw error
    return data
  },

  async updatePointsBalance(userId: string, pointsDelta: number, ledgerEntry: {
    type: string
    amount: number
    orderId?: string
    productId?: string
    reason?: string
    adminUserId?: string
    expiresAt?: Date
  }) {
    // Use a Postgres function for atomic update (replaces Firestore transactions)
    const { data, error } = await adminSupabase.rpc('add_points_transaction', {
      p_user_id: userId,
      p_type: ledgerEntry.type,
      p_amount: ledgerEntry.amount,
      p_order_id: ledgerEntry.orderId ?? undefined,
      p_product_id: ledgerEntry.productId ?? undefined,
      p_reason: ledgerEntry.reason ?? undefined,
      p_admin_user_id: ledgerEntry.adminUserId ?? undefined,
      p_expires_at: ledgerEntry.expiresAt?.toISOString() ?? undefined,
    })
    if (error) throw error
    return data
  },

  // ── VEHICLES ───────────────────────────────────────────────

  async getVehicleMakes(year: number, type?: string) {
    let query = adminSupabase
      .from('vehicles')
      .select('make')
      .eq('year', year)
      .order('make')
    if (type) query = query.eq('type', type)
    const { data, error } = await query
    if (error) throw error
    return [...new Set(data.map((v: any) => v.make))]
  },

  async getVehicleModels(year: number, make: string) {
    const { data, error } = await adminSupabase
      .from('vehicles')
      .select('model, submodel, id')
      .eq('year', year)
      .eq('make', make)
      .order('model')
    if (error) throw error
    return data
  },

  // ── ORDERS ─────────────────────────────────────────────────

  async createOrder(orderData: Record<string, unknown>) {
    const { data, error } = await adminSupabase
      .from('orders')
      .insert(orderData as any)
      .select()
      .single()
    if (error) throw error
    return data
  },

  async getOrderWithDetails(orderId: string) {
    const { data, error } = await adminSupabase
      .from('orders')
      .select(`
        *,
        order_items (*),
        vendor_orders (*),
        order_timeline (*)
      `)
      .eq('id', orderId)
      .single()
    if (error) throw error
    return data
  },

  async getUserOrders(userId: string, limit = 20, offset = 0) {
    const { data, error, count } = await adminSupabase
      .from('orders')
      .select('*, order_items (*)', { count: 'exact' })
      .eq('user_id', userId)
      .not('status', 'in', '("pending_payment","payment_failed")')
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1)
    if (error) throw error
    return { orders: data, total: count }
  },

  // ── CART ───────────────────────────────────────────────────

  async getOrCreateCart(userId: string) {
    // Try to find existing active cart
    const { data: existing } = await adminSupabase
      .from('carts')
      .select('*, cart_items (*, products (sku, name, our_price, map_floor, in_stock, product_images (*)))')
      .eq('user_id', userId)
      .eq('status', 'active')
      .order('created_at', { ascending: false })
      .limit(1)
      .single()

    if (existing) return existing

    // Create new cart
    const { data, error } = await adminSupabase
      .from('carts')
      .insert({ user_id: userId })
      .select()
      .single()
    if (error) throw error
    return data
  },

  // ── MAP COMPLIANCE ─────────────────────────────────────────

  async getMAPViolations() {
    const { data, error } = await adminSupabase
      .from('map_compliance')   // our VIEW from the schema
      .select('*')
      .eq('compliance_status', 'violation')
      .order('violation_amount', { ascending: false })
    if (error) throw error
    return data
  },

  async getCompetitorPricing(limit = 100, recommendation?: string) {
    let query = adminSupabase
      .from('competitor_pricing')
      .select('*, products (sku, name, our_price, map_floor)')
      .order('last_checked_at', { ascending: true, nullsFirst: true })
      .limit(limit)
    if (recommendation) query = query.eq('recommendation', recommendation)
    const { data, error } = await query
    if (error) throw error
    return data
  },

  // ── MAP AUDIT LOG ──────────────────────────────────────────
  // Call logMapCheck() any time a price is set or checked.
  // Four trigger sources:
  //   'sync'             — PU or WPS sync after upsert
  //   'manual'           — admin changes our_price in /admin/products
  //   'auto_correct'     — MAP monitor raises price to map_floor
  //   'scheduled_check'  — nightly Vercel cron baseline audit

  async logMapCheck(entry: {
    sku: string
    productName: string
    brandName: string
    mapFloor: number
    ourPrice: number
    trigger: 'sync' | 'manual' | 'auto_correct' | 'scheduled_check'
    vendor?: string
    productId?: string
    correctedBy?: string       // auth user id — manual edits only
    previousPrice?: number     // auto_correct only
    notes?: string
  }) {
    const delta = entry.ourPrice - entry.mapFloor

    // Determine status
    let status: 'compliant' | 'violation' | 'corrected'
    if (entry.trigger === 'auto_correct' || entry.trigger === 'manual') {
      status = delta >= 0 ? 'corrected' : 'violation'
    } else {
      status = delta >= 0 ? 'compliant' : 'violation'
    }

    const { error } = await adminSupabase
      .from('map_audit_log')
      .insert({
        product_id:     entry.productId ?? null,
        sku:            entry.sku,
        product_name:   entry.productName,
        brand_name:     entry.brandName,
        map_floor:      entry.mapFloor,
        our_price:      entry.ourPrice,
        delta,
        status,
        trigger:        entry.trigger,
        vendor:         entry.vendor ?? null,
        corrected_by:   entry.correctedBy ?? null,
        corrected_at:   entry.trigger === 'auto_correct' || entry.trigger === 'manual'
                          ? new Date().toISOString()
                          : null,
        previous_price: entry.previousPrice ?? null,
        notes:          entry.notes ?? null,
      })

    if (error) {
      // Never throw — a logging failure must not break a sync or checkout
      console.error('[MAP audit] log failed:', error.message, { sku: entry.sku })
    }

    return status
  },

  // Bulk version for syncs — logs all products in one shot
  // Pass the array of upserted products from PU or WPS sync
  async logMapCheckBulk(products: Array<{
    id?: string
    sku: string
    name: string
    brand_name: string
    map_floor: number
    our_price: number
    vendor_slug?: string
  }>, trigger: 'sync' | 'scheduled_check') {
    const rows = products
      .filter(p => p.map_floor != null && p.our_price != null)
      .map(p => {
        const delta = p.our_price - p.map_floor
        return {
          product_id:   p.id ?? null,
          sku:          p.sku,
          product_name: p.name,
          brand_name:   p.brand_name ?? 'Unknown',
          map_floor:    p.map_floor,
          our_price:    p.our_price,
          delta,
          status:       delta >= 0 ? 'compliant' : 'violation',
          trigger,
          vendor:       p.vendor_slug ?? null,
        }
      })

    if (rows.length === 0) return

    // Insert in batches of 500 to avoid payload limits
    const BATCH = 500
    for (let i = 0; i < rows.length; i += BATCH) {
      const { error } = await adminSupabase
        .from('map_audit_log')
        .insert(rows.slice(i, i + BATCH))
      if (error) {
        console.error('[MAP audit] bulk log failed at batch', i, error.message)
      }
    }

    // Return violation count for sync log
    return rows.filter(r => r.status === 'violation').length
  },

  async getMAPAuditLog(filters: {
    from?: string
    to?: string
    brand?: string
    sku?: string
    vendor?: string
    status?: 'all' | 'compliant' | 'violation' | 'corrected'
    limit?: number
    offset?: number
  } = {}) {
    let query = adminSupabase
      .from('map_audit_log')
      .select('*', { count: 'exact' })
      .order('checked_at', { ascending: false })

    if (filters.from)   query = query.gte('checked_at', filters.from)
    if (filters.to)     query = query.lte('checked_at', filters.to)
    if (filters.brand)  query = query.ilike('brand_name', `%${filters.brand}%`)
    if (filters.sku)    query = query.ilike('sku', `%${filters.sku}%`)
    if (filters.vendor) query = query.eq('vendor', filters.vendor)
    if (filters.status && filters.status !== 'all')
                        query = query.eq('status', filters.status)

    const limit  = filters.limit  ?? 100
    const offset = filters.offset ?? 0
    query = query.range(offset, offset + limit - 1)

    const { data, error, count } = await query
    if (error) throw error
    return { entries: data ?? [], total: count ?? 0 }
  },

  async getMAPAuditSummary(from: string, to: string) {
    type MapAuditSummaryRow = Pick<
      Database['public']['Tables']['map_audit_log']['Row'],
      'status' | 'trigger' | 'checked_at' | 'corrected_at'
    >

    const { data, error } = await adminSupabase
      .from('map_audit_log')
      .select('status, trigger, checked_at, corrected_at')
      .gte('checked_at', from)
      .lte('checked_at', to)
      .returns<MapAuditSummaryRow[]>()

    if (error) throw error
    if (!data) return null

    const total         = data.length
    const compliant     = data.filter(r => r.status === 'compliant').length
    const violations    = data.filter(r => r.status === 'violation').length
    const corrected     = data.filter(r => r.status === 'corrected').length
    const autoCorrected = data.filter(r => r.trigger === 'auto_correct').length
    const manualFixed   = data.filter(r => r.trigger === 'manual' && r.status === 'corrected').length

    // Avg violation duration in ms
    const durations = data
      .filter(r => r.status === 'corrected' && r.corrected_at)
      .map(r => new Date(r.corrected_at!).getTime() - new Date(r.checked_at).getTime())
    const avgViolationMs = durations.length
      ? Math.round(durations.reduce((a, b) => a + b, 0) / durations.length)
      : 0

    return {
      total,
      compliant,
      violations,
      corrected,
      autoCorrected,
      manualFixed,
      complianceRate: total > 0 ? ((compliant + corrected) / total * 100).toFixed(2) : '100.00',
      avgViolationMs,
      avgViolationMin: Math.round(avgViolationMs / 60000),
    }
  },

  // ── ADMIN ──────────────────────────────────────────────────

  async getDashboardMetrics() {
    const { data, error } = await adminSupabase
      .from('dashboard_today' as any)   // our VIEW
      .select('*')
      .single()
    if (error) throw error

    // Also get active/abandoned cart counts
    const { count: activeCarts } = await adminSupabase
      .from('carts')
      .select('*', { count: 'exact', head: true })
      .eq('status', 'active')
      .gt('total', 0)

    const { count: abandonedCarts } = await adminSupabase
      .from('carts')
      .select('*', { count: 'exact', head: true })
      .eq('status', 'abandoned')
      .gte('created_at', new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString())

    const { count: mapViolations } = await adminSupabase
      .from('map_compliance')
      .select('*', { count: 'exact', head: true })
      .eq('compliance_status', 'violation')

    return {
      ...(data as unknown as Record<string, unknown>),
      active_carts: activeCarts,
      abandoned_carts: abandonedCarts,
      map_violations: mapViolations,
    }
  },
}
